# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

opt_out_usage

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test", gradle_path: '../gradlew')
  end

  desc "Deploy a new version to the Google Play beta track"
  lane :deploy do
    gradle(task: "clean assembleRelease", gradle_path: '../gradlew')
    upload_to_play_store(track: 'beta', skip_upload_images: 'true', skip_upload_screenshots: 'true', validate_only: 'true')
  end
end

# vi:syntax=ruby
